"""initial_schema

Revision ID: 84f0a3a04ce0
Revises: 
Create Date: 2026-03-03 16:56:49.460978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f0a3a04ce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financials_stock_id'), ['stock_id'], unique=False)

    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_holdings_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_holdings_portfolio_id'))

    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financials_stock_id'))

    # ### end Alembic commands ###
