"""Add target prices and memo to user_watchlist

Revision ID: dccad703004b
Revises: c861d0959216
Create Date: 2026-04-14 23:17:17.054896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccad703004b'
down_revision: Union[str, Sequence[str], None] = 'c861d0959216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watchlist')
    with op.batch_alter_table('market_regime_history', schema=None) as batch_op:
        batch_op.alter_column('forward_pe',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('strategy_state', schema=None) as batch_op:
        batch_op.drop_column('tick_trade')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tick_trade', sa.TEXT(), nullable=False))

    with op.batch_alter_table('market_regime_history', schema=None) as batch_op:
        batch_op.alter_column('forward_pe',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    op.create_table('user_watchlist',
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), nullable=False),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'ticker')
    )
    # ### end Alembic commands ###
