"""Recreate user_watchlist with target prices and memo

Revision ID: eac4352b0fb3
Revises: dccad703004b
Create Date: 2026-04-14 23:19:06.691506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac4352b0fb3'
down_revision: Union[str, Sequence[str], None] = 'dccad703004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watchlist',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('target_buy_price', sa.Float(), nullable=True),
    sa.Column('target_sell_price', sa.Float(), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watchlist')
    # ### end Alembic commands ###
