from pydantic import BaseModel, Field
from typing import Optional

class OverseasDetailPriceResponse(BaseModel):
    """KIS 해외 주식 상세 시세 응답 스키마 (HHDFS70200200)"""
    rsym: Optional[str] = Field(None, description="실시간조회종목코드")
    pvol: Optional[str] = Field(None, description="전일거래량")
    open: Optional[str] = Field(None, description="시가")
    high: Optional[str] = Field(None, description="고가")
    low: Optional[str] = Field(None, description="저가")
    last: Optional[str] = Field(None, description="현재가")
    base: Optional[str] = Field(None, description="전일종가")
    tomv: Optional[str] = Field(None, description="시가총액")
    pamt: Optional[str] = Field(None, description="전일거래대금")
    uplp: Optional[str] = Field(None, description="상한가")
    dnlp: Optional[str] = Field(None, description="하한가")
    h52p: Optional[str] = Field(None, description="52주최고가")
    h52d: Optional[str] = Field(None, description="52주최고일자")
    l52p: Optional[str] = Field(None, description="52주최저가")
    l52d: Optional[str] = Field(None, description="52주최저일자")
    perx: Optional[str] = Field(None, description="PER")
    pbrx: Optional[str] = Field(None, description="PBR")
    epsx: Optional[str] = Field(None, description="EPS")
    bpsx: Optional[str] = Field(None, description="BPS")
    shar: Optional[str] = Field(None, description="상장주수")
    mcap: Optional[str] = Field(None, description="자본금")
    curr: Optional[str] = Field(None, description="통화")
    zdiv: Optional[str] = Field(None, description="소수점자리수")
    vnit: Optional[str] = Field(None, description="매매단위")
    t_xprc: Optional[str] = Field(None, description="원환산당일가격")
    t_xdif: Optional[str] = Field(None, description="원환산당일대비")
    t_xrat: Optional[str] = Field(None, description="원환산당일등락")
    p_xprc: Optional[str] = Field(None, description="원환산전일가격")
    p_xdif: Optional[str] = Field(None, description="원환산전일대비")
    p_xrat: Optional[str] = Field(None, description="원환산전일등락")
    t_rate: Optional[str] = Field(None, description="당일환율")
    p_rate: Optional[str] = Field(None, description="전일환율")
    t_xsgn: Optional[str] = Field(None, description="원환산당일기호")
    p_xsng: Optional[str] = Field(None, description="원환산전일기호")
    e_ordyn: Optional[str] = Field(None, description="거래가능여부")
    e_hogau: Optional[str] = Field(None, description="호가단위")
    e_icod: Optional[str] = Field(None, description="업종(섹터)")
    e_parp: Optional[str] = Field(None, description="액면가")
    tvol: Optional[str] = Field(None, description="거래량")
    tamt: Optional[str] = Field(None, description="거래대금")
    etyp_nm: Optional[str] = Field(None, description="ETP 분류명")
    hnam: Optional[str] = Field(None, description="종목한글명") # 스펙상 없으나 실제 응답에 포함됨
