from pydantic import BaseModel, Field
from typing import Optional

class OverseasDetailPriceResponse(BaseModel):
    """KIS 해외 주식 상세 시세 응답 스키마 (HHDFS70200200)"""
    rsym: Optional[str] = Field(None, description="Real-time ticker code")
    pvol: Optional[str] = Field(None, description="Previous day volume")
    open: Optional[str] = Field(None, description="Open price")
    high: Optional[str] = Field(None, description="High price")
    low: Optional[str] = Field(None, description="Low price")
    last: Optional[str] = Field(None, description="Current price")
    base: Optional[str] = Field(None, description="Previous close price")
    tomv: Optional[str] = Field(None, description="Market capitalization")
    pamt: Optional[str] = Field(None, description="Previous day trading amount")
    uplp: Optional[str] = Field(None, description="Upper limit price")
    dnlp: Optional[str] = Field(None, description="Lower limit price")
    h52p: Optional[str] = Field(None, description="52-week high price")
    h52d: Optional[str] = Field(None, description="52-week high date")
    l52p: Optional[str] = Field(None, description="52-week low price")
    l52d: Optional[str] = Field(None, description="52-week low date")
    perx: Optional[str] = Field(None, description="PER")
    pbrx: Optional[str] = Field(None, description="PBR")
    epsx: Optional[str] = Field(None, description="EPS")
    bpsx: Optional[str] = Field(None, description="BPS")
    shar: Optional[str] = Field(None, description="Listed shares")
    mcap: Optional[str] = Field(None, description="Capital")
    curr: Optional[str] = Field(None, description="Currency")
    zdiv: Optional[str] = Field(None, description="Decimal places")
    vnit: Optional[str] = Field(None, description="Trading unit")
    t_xprc: Optional[str] = Field(None, description="KRW-converted today's price")
    t_xdif: Optional[str] = Field(None, description="KRW-converted today's change")
    t_xrat: Optional[str] = Field(None, description="KRW-converted today's change rate")
    p_xprc: Optional[str] = Field(None, description="KRW-converted previous day's price")
    p_xdif: Optional[str] = Field(None, description="KRW-converted previous day's change")
    p_xrat: Optional[str] = Field(None, description="KRW-converted previous day's change rate")
    t_rate: Optional[str] = Field(None, description="Today's exchange rate")
    p_rate: Optional[str] = Field(None, description="Previous day's exchange rate")
    t_xsgn: Optional[str] = Field(None, description="KRW-converted today's sign")
    p_xsng: Optional[str] = Field(None, description="KRW-converted previous day's sign")
    e_ordyn: Optional[str] = Field(None, description="Tradable flag")
    e_hogau: Optional[str] = Field(None, description="Tick size unit")
    e_icod: Optional[str] = Field(None, description="Industry (sector)")
    e_parp: Optional[str] = Field(None, description="Par value")
    tvol: Optional[str] = Field(None, description="Volume")
    tamt: Optional[str] = Field(None, description="Trading amount")
    etyp_nm: Optional[str] = Field(None, description="ETP classification name")
    hnam: Optional[str] = Field(None, description="Stock Korean name") # 스펙상 없으나 실제 응답에 포함됨
